# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #    
#                                                                                               #
#                                     Vanilla Challenges                                        #
#                                   Created by eliotesta98                                      #
#                                                                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #   

Configuration:
  # List of Challenges
  Challenges:
    # BlockPlaceChallenge
    BlockPlace:
      TypeChallenge: 'BlockPlaceChallenge'
      # Block you want placed for challenge, if you want all blocks write ALL
      Block: ALL
      # Block you want place the block, if you want all write ALL
      BlockOnPlaced: GRASS_BLOCK
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Block Placer Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Place blocks on Grass Block for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'TURTLE_HELMET:1'
    BlockBreaker:
      TypeChallenge: 'BlockBreakChallenge'
      # Block you want break for challenge, if you want all blocks write ALL
      Block: ALL
      # Type of item in main hand for break this blocks, if you want all items write ALL
      ItemInHand: ALL
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Breaker Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Break all type of block for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'TOTEM_OF_UNDYING:1'
    Crafter:
      TypeChallenge: 'CraftingChallenge'
      # Item you want crafting for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Crafting Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Craft any item for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'GHAST_TEAR:2'
    Cooker:
      TypeChallenge: 'CookerChallenge'
      # Item you want cook for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Cook Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Cook any item for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'DRAGON_HEAD:1'
    Consumer:
      TypeChallenge: 'ConsumeChallenge'
      # Item you want to consume for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Consume Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Consume any item for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'WITHER_SKELETON_SKULL:1'
    ExpCollector:
      TypeChallenge: 'CollectorExpChallenge'
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Collect Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Collect Experience for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'DRAGON_HEAD:1'
    Killer:
      TypeChallenge: 'KillChallenge'
      # Mob you want to kill for challenge, if you want all mobs write ALL
      Mob: ALL
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Kill Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Kill any mob for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'WITHER_SKELETON_SKULL:1'
    Breeder:
      TypeChallenge: 'BreedChallenge'
      # Mob you want to breed for challenge, if you want all mobs write ALL
      Mob: ALL
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Breed Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Breed mob for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NAME_TAG:2'
    Feeder:
      TypeChallenge: 'FeedChallenge'
      # Item you want to feed for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Feed Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Eat items or starve for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'ENDER_PEARL:4'
    Shooter:
      TypeChallenge: 'ShootChallenge'
      # Force you want to apply for shoot arrow in challenge, if you want to disable use 0.0
      Force: 1.0
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Shoot Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Shoot arrows at max power for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'HEART_OF_THE_SEA:1'
    JumperHorse:
      TypeChallenge: 'JumpWithHorseChallenge'
      # Power you want to apply for jump with horse in challenge, if you want to disable use 0.0
      Power: 0.5
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Jump With Horse Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Jump with Horse at middle or plus power for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'SCUTE:2'
    Dyer:
      TypeChallenge: 'ColorSheepChallenge'
      # Color you want to use for challenge, if you want all colors write ALL
      Color: ALL
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Color Sheep Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Color a Sheep with dye for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'TOTEM_OF_UNDYING:1'
    Raider:
      TypeChallenge: 'RaidChallenge'
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Raid Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Win raid for receive points (100 points for waves at complete)'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'IRON_INGOT:64'
    Fisher:
      TypeChallenge: 'FishingChallenge'
      # Item you want to fish for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Fishing Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Fishing for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'GOLD_INGOT:32'
    Sprinter:
      TypeChallenge: 'SprintChallenge'
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Sprint Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Toggle Sprint for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'DIAMOND:16'
    Mover:
      TypeChallenge: 'MoveChallenge'
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Move Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Move for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'EMERALD:16'
    Damager:
      TypeChallenge: 'DamageChallenge'
      # Cause you want to damage for challenge, if you want all causes write ALL
      Cause: ALL
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Damage Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Take damage for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'TOTEM_OF_UNDYING:1'
    Sneaker:
      TypeChallenge: 'SneakChallenge'
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Sneak Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Sneak for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'ZOMBIE_VILLAGER_SPAWN_EGG:1'
    ItemBreaker:
      TypeChallenge: 'ItemBreakChallenge'
      # Item you want to break for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Break Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Break an item for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'ZOMBIE_VILLAGER_SPAWN_EGG:1'
    Absorber:
      TypeChallenge: 'SpongeAbsorbChallenge'
      # Title challenge
      Title: '&5[Vanilla Challenge] &7Sponge Absorb Challenge'
      # Description of Challenge
      Description: '&5[Vanilla Challenge] &7Absorb fluids with Sponge for receive points (1 point for 1 source)'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'TNT:32'
  BroadcastMessage:
    # time in minutes 0 to disabled
    TimeTitleChallenges: 10
# Messages
Message:
  commandFooter: '&7(&7&l(&c&l!&7&l)&7) &9&l[] optional value, <> required'
  commandVcReloadHelp: '&e/vc &6<reload> &7command reload Plugin'
  commandVcHelpHelp: '&e/vc &6<help> &7command help for VanillaChallenge Plugin'
  commandVcNextHelp: '&e/vc &6<next> &7go to the next challenge'
  commandVcTopHelp: '&e/vc &6<top> &7for see the top 3'
  commandVcPointsHelp: '&e/vc &6<points> [playerName] &7for see your points or points of another player'
  commandVcClear: '&e/vc &6<clear> &7for clear all Challenges and player Points'
  commandVcChallenge: '&e/vc &6<challenge> &7for see the daily challenge selected and time resume'
  commandVcAddChallenge: '&e/vc &6<add> <playername> <points> &7for set points of a player'

  errorYouAreNotAPlayer: '&cYou are not a player'
  errorCommandNotFound: '&cCommand not found'
  errorNoPerms: '&cInsufficient permission'

  pointsInfo: '&e{player} &7points are &b{number}'
  timeInfo: '&5[Vanilla Challenge] &7{hours} hours to the end of the challenge'
  actuallyInTop: '&5[Vanilla Challenge] &7Actually in top there are:'
  topPlayers:
    - '&6{number}° &e{player}&7 with &b{points}&7 points'
    - '&7{number}° &e{player}&7 with &b{points}&7 points'
    - '&8{number}° &e{player}&7 with &b{points}&7 points'
  challengeReward: '&5[Vanilla Challenge] &7You complete the challenge and arrive at top 3 players, receive x&b{number}&7 of &e{item}'

Debug:
  # Commands time execution
  Commands: false
  # Block Place Event time execution
  BlockPlaceEvent: false
  # Block Break Event time execution
  BlockBreakEvent: false
  # Daily Give Reward Event time execution
  DailyGiveRewardEvent: false
  # Craft Item Event time execution
  CraftItemEvent: false
  # Furnace Cook Event time execution
  FurnaceCookEvent: false
  # Item Consume Event time execution
  ItemConsumeEvent: false
  # Exp Collector Event time execution
  ExpCollectorEvent: false
  # Kill Event time execution
  KillEvent: false
  # Breed Event time execution
  BreedEvent: false
  # Feed Event time execution
  FeedEvent: false
  # Shoot Arrow Event time execution
  ShootArrowEvent: false
  # Jump Horse Event time execution
  JumpHorseEvent: false
  # Color Sheep Event time execution
  ColorSheepEvent: false
  # Raid Event time execution
  RaidEvent: false
  # Fish Event time execution
  FishEvent: false
  # Eat Event time execution
  EatEvent: false
  # Sprint Event time execution
  SprintEvent: false
  # Move Event time execution
  MoveEvent: false
  # Damage Event time execution
  DamageEvent: false
  # Sneak Event time execution
  SneakEvent: false
  # Item Break Event time execution
  ItemBreakEvent: false
  # Sponge Absorb Event time execution
  SpongeAbsorbEvent: false
  # Enabled time execution
  Enabled: false
  # Disabled time execution
  Disabled: false
