# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #    
#                                                                                               #
#                                     Vanilla Challenges                                        #
#                                   Created by eliotesta98                                      #
#                                                                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #   

Configuration:
  # List of Challenges
  Challenges:
    # BlockPlaceChallenge
    BlockPlace:
      TypeChallenge: 'BlockPlaceChallenge'
      # Block you want placed for challenge, if you want all blocks write ALL
      Block: ALL
      # Block you want place the block, if you want all write ALL
      BlockOnPlaced: GRASS_BLOCK
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aBlock Placer Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &ePlace blocks on Grass Block for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    BlockBreaker:
      TypeChallenge: 'BlockBreakChallenge'
      # Block you want break for challenge, if you want all blocks write ALL
      Block: ALL
      # Type of item in main hand for break this blocks, if you want all items write ALL
      ItemInHand: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aBreaker Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eBreak all type of block for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Crafter:
      TypeChallenge: 'CraftingChallenge'
      # Item you want crafting for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aCrafting Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eCraft any item for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Cooker:
      TypeChallenge: 'CookerChallenge'
      # Item you want cook for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aCook Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eCook any item for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Consumer:
      TypeChallenge: 'ConsumeChallenge'
      # Item you want to consume for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aConsume Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eConsume any item for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    ExpCollector:
      TypeChallenge: 'CollectorExpChallenge'
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aCollect Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eCollect Experience for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Killer:
      TypeChallenge: 'KillChallenge'
      # Mob you want to kill for challenge, if you want all mobs write ALL
      Mob: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aKill Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eKill any mob for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Breeder:
      TypeChallenge: 'BreedChallenge'
      # Mob you want to breed for challenge, if you want all mobs write ALL
      Mob: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aBreed Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eBreed mob for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Feeder:
      TypeChallenge: 'FeedChallenge'
      # Item you want to feed for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aFeed Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eEat items or starve for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Shooter:
      TypeChallenge: 'ShootChallenge'
      # Force you want to apply for shoot arrow in challenge, if you want to disable use 0.0
      Force: 1.0
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aShoot Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eShoot arrows at max power for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    JumperHorse:
      TypeChallenge: 'JumpWithHorseChallenge'
      # Power you want to apply for jump with horse in challenge, if you want to disable use 0.0
      Power: 0.5
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aJump With Horse Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eJump with Horse at middle or plus power for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Dyer:
      TypeChallenge: 'ColorSheepChallenge'
      # Color you want to use for challenge, if you want all colors write ALL
      Color: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aColor Sheep Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eColor a Sheep with dye for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
  BroadcastMessage:
    # time in minutes 0 to disabled
    TimeTitleChallenges: 10
# Messages
Message:
  commandFooter: '&7(&7&l(&c&l!&7&l)&7) &9&l[] optional value, <> required'
  commandVcReloadHelp: '&e/vc &6<reload> &7command reload Plugin'
  commandVcHelpHelp: '&e/vc &6<help> &7command help for VanillaChallenge Plugin'
  commandVcNextHelp: '&e/vc &6<next> &7go to the next challenge'
  commandVcTopHelp: '&e/vc &6<top> &7for see the top 3'
  commandVcPointsHelp: '&e/vc &6<points> [playerName] &7for see your points or points of another player'

  errorYouAreNotAPlayer: '&cYou are not a player'
  errorCommandNotFound: '&cCommand not found'
  errorNoPerms: '&cInsufficient permission'

  pointsInfo: '&a&l{player} points are {number}'
  actuallyInTop: '&c&l[Vanilla Challenge] &a&lActually in top there are:'
  topPlayers: '&a&l{number}° place: {player} with {points} points'
  challengeReward: '&c&l[Vanilla Challenge] &a&lYou complete the challenge and arrive at top 3 players, receive x{number} of {item}'

Debug:
  # Commands time execution
  Commands: false
  # Block Place Event time execution
  BlockPlaceEvent: false
  # Block Break Event time execution
  BlockBreakEvent: false
  # Daily Give Reward Event time execution
  DailyGiveRewardEvent: false
  # Craft Item Event time execution
  CraftItemEvent: false
  # Furnace Cook Event time execution
  FurnaceCookEvent: false
  # Item Consume Event time execution
  ItemConsumeEvent: false
  # Exp Collector Event time execution
  ExpCollectorEvent: false
  # Kill Event time execution
  KillEvent: false
  # Breed Event time execution
  BreedEvent: false
  # Feed Event time execution
  FeedEvent: false
  # Shoot Arrow Event time execution
  ShootArrowEvent: false
  # Jump Horse Event time execution
  JumpHorseEvent: false
  # Color Sheep Event time execution
  ColorSheepEvent: false
  # Enabled time execution
  Enabled: false
  # Disabled time execution
  Disabled: false
